from __future__ import print_function
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint
from datetime import date, datetime

# Configure API key authorization: APIKey
configuration = swagger_client.Configuration()
configuration.api_key['Authorization'] = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJwMWpGZWhGZTB4cHJiT05OMWxsenBHYUN1UkNhN1VIMGxNNTl4UDZURkpzIiwiaWF0IjoxNzAzMTM4ODY4fQ.1pTAXxfPAJ64BzqxaRU9xnFPflsJ0niKPDC6BBmDpkk'
configuration.api_key_prefix['Authorization'] = 'apiKey'

# create an instance of the API class
api_instance = swagger_client.DefaultApi(swagger_client.ApiClient(configuration))
output_format = 'rapidJSON' # str | Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output. 
coord_output_format = 'EPSG:4326' # str | This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format.
dep_arr_macro = 'dep' # str | This value anchors the requested date time. If set to `dep`, then trips *departing after* the specified date/time *at the specified location* are included. If set to `arr`, then trips *arriving before* the specified time *at its destination stop* are included. Works in conjunctions with the `itdDate` and `itdTime` values. 
type_origin = 'any' # str | This is the type of data specified in the `name_origin` field. The origin indicates the starting point when searching for journeys. The best way to use the trip planner is to use use `any` for this field then specify a valid location ID in `type_origin`, or to use `coord` in this field and a correctly formatted coordinate in `type_origin`.  (default to any)
name_origin = '2150412' # str | This value is used to indicate the starting point when searching for journeys. This value can be one of three things: A valid location/stop ID (for example, `10101100` indicates Central Station - this can be determined using `stop_finder`). A valid global stop ID (for example, `200060` indicates Central Station - this can be determined using `stop_finder`) Coordinates in the format `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first).  (default to 10101331)
type_destination = 'any' # str | This is the type of data specified in the `name_destination` field. The origin indicates the finishing point when searching for journeys. The best way to use the trip planner is to use use `any` for this field then specify a valid location ID in `type_destination`, or to use `coord` in this field and a correctly formatted coordinate in `type_destination`.  (default to any)
name_destination = '212111' # str | This value is used to indicate the finishing point when searching for journeys. This value can be one of three things: A valid location/stop ID (for example, `10101100` indicates Central Station - this can be determined using `stop_finder`). A valid global stop ID (for example, `200060` indicates Central Station - this can be determined using `stop_finder`) Coordinates in the format `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first).  (default to 10102027)
#itd_date = '20161001' # str | The reference date used when searching trips, in `YYYYMMDD` format. For instance, `20160901` refers to 1 September 2016. Works in conjunction with the `itdTime` and `depArrMacro` values. If not specified, the current server date is used.  (optional) (default to 20161001)
#itd_time = '1200' # str | The reference time used when searching trips, in `HHMM` 24-hour format. For instance, `2215` refers to 10:15 PM. | Works in conjunction with the `itdDate` and `depArrMacro` values. If not specified, the current server time is used.  (optional) (default to 1200)
calc_number_of_trips = 6 # int | This parameter indicates the maximum number of trips to returned. Fewer trips may be returned anyway, depending on the available public transport services.  (optional) (default to 6)
# wheelchair = 'wheelchair_example' # str | Including this parameter (regardless of its value) ensures that only wheelchair-accessible options are returned.  (optional)
# excluded_means = 'excluded_means_example' # str | This parameter which means of transport to exclude from the trip plan. To exclude one means, select one of the following: `1` = train, `2` = metro, `4` = light rail, `5` = bus, `7` = coach, `9` = ferry, `11` = school bus. `checkbox` allows you to exclude more than one means of transport when used in conjunction with the `exclMOT_<ID>` parameters.  (optional)
# excl_mot_1 = 'excl_mot_1_example' # str | Excludes train services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox`  (optional)
# excl_mot_2 = 'excl_mot_2_example' # str | Excludes metro services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox`  (optional)
# excl_mot_4 = 'excl_mot_4_example' # str | Excludes light rail services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox`  (optional)
# excl_mot_5 = 'excl_mot_5_example' # str | Excludes bus services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox`  (optional)
excl_mot_7 = '7' # str | Excludes coach services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox`  (optional)
excl_mot_9 = '9' # str | Excludes ferry services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox`  (optional)
# excl_mot_11 = 'excl_mot_11_example' # str | Excludes school bus services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox`  (optional)
tf_nswtr = 'true' # str | Including this parameter enables a number of options that result in this API call operating in the same way as the Transport for NSW Trip Planner web site, including enabling real-time data.  (optional) (default to true)
version = '10.2.1.42' # str | Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected.  (optional) (default to 10.2.1.42)
it_options_active = 1 # int | This parameter activates the options for individual transport. If the parameter is disabled, the parameters concerning individual transport will not be taken into account. possible values are 0 and 1  (optional) (default to 1)
compute_monomodal_trip_bicycle = True # bool | Activates the calculation of a monomodal trip, i.e., a trip that takes place exclusively with the means of transport <means of transport>, e.g., with bicycle. Note 1: In order to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Note 2: If no monomodal trip with the means of transport <means of transport> is calculated despite the parameter, the maximum time is often set too low. The parameter MaxITTime applies to all means of transport, the parameter MaxITTime<means of transport>to the means of transport <means of transport> (e.g., MaxITTime107). These parameters are located in the [Parameters] section or are added to it. The configuration can be alternatively overridden bythe maxTime<Transport means> parameter.  (optional)
cycle_speed = 16 # int | The value of the <speed> parameter is used to specify the speed of cycle travel in kilometers per hour.Note: In order to use this parameter, the options for individual transport must be activated with itOptionsActive=1. If the parameter is to be specified together with a profile, the bikeProfSpeed parameter can be used.The parameter “'cycleSpeed” specifies the desired real speed of the user for the bike route, which overwrites the speed in the SpeedSettings of the corresponding “bikeProfSpeed”.  (optional) (default to 16)
bike_prof_speed = 'bike_prof_speed_example' # str | With the parameter 'bikeProfSpeed' a bike profile name is passed  (optional)
max_time_bicycle = 56 # int | The value of the this parameter sets the maximum time to be covered by the means of cycling. The time is specified in minutes. Note: To use this parameter, the options for individual transport must be enabled with itOptionsActive=1  (optional)
only_it_bicycle = 56 # int | Restricts the calculation to trips with the bikes only. Note: To be able to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Possible values are 1, true, on  (optional)
use_elevation_data = 56 # int | If this parameter is active, the elevation data is taken into account in the trip calculation for all means of transport and output in a route description for each individual transport section. Note: To be able to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Possible values are 1, true, on  (optional)
elev_fac = 56 # int | This parameter specifies the maximum slope for bike routes. Roads with a slope greater than the specified?? one are avoided. The slope is specified by a factor <factor> whose value range is [0..100]. By default, the value of the parameter is 50  (optional)

try:
    # Provides capability to provide NSW public transport trip plan options, including walking and driving legs and real-time information.
    api_response = api_instance.tfnsw_trip_request2(output_format, coord_output_format, dep_arr_macro, type_origin, name_origin, type_destination, name_destination, calc_number_of_trips=calc_number_of_trips, excl_mot_7=excl_mot_7, excl_mot_9=excl_mot_9, tf_nswtr=tf_nswtr, version=version, it_options_active=it_options_active, compute_monomodal_trip_bicycle=compute_monomodal_trip_bicycle, cycle_speed=cycle_speed, bike_prof_speed=bike_prof_speed, max_time_bicycle=max_time_bicycle, only_it_bicycle=only_it_bicycle, use_elevation_data=use_elevation_data, elev_fac=elev_fac)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling DefaultApi->tfnsw_trip_request2: %s\n" % e)