# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.2.1.42
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdditionalInfoResponseInfos(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'affected': 'AdditionalInfoResponseInfosAffected',
        'current': 'list[AdditionalInfoResponseMessage]',
        'historic': 'list[AdditionalInfoResponseMessage]'
    }

    attribute_map = {
        'affected': 'affected',
        'current': 'current',
        'historic': 'historic'
    }

    def __init__(self, affected=None, current=None, historic=None):  # noqa: E501
        """AdditionalInfoResponseInfos - a model defined in Swagger"""  # noqa: E501
        self._affected = None
        self._current = None
        self._historic = None
        self.discriminator = None
        if affected is not None:
            self.affected = affected
        if current is not None:
            self.current = current
        if historic is not None:
            self.historic = historic

    @property
    def affected(self):
        """Gets the affected of this AdditionalInfoResponseInfos.  # noqa: E501


        :return: The affected of this AdditionalInfoResponseInfos.  # noqa: E501
        :rtype: AdditionalInfoResponseInfosAffected
        """
        return self._affected

    @affected.setter
    def affected(self, affected):
        """Sets the affected of this AdditionalInfoResponseInfos.


        :param affected: The affected of this AdditionalInfoResponseInfos.  # noqa: E501
        :type: AdditionalInfoResponseInfosAffected
        """

        self._affected = affected

    @property
    def current(self):
        """Gets the current of this AdditionalInfoResponseInfos.  # noqa: E501

        This specifies the list of current service alerts based on the specified filters.  # noqa: E501

        :return: The current of this AdditionalInfoResponseInfos.  # noqa: E501
        :rtype: list[AdditionalInfoResponseMessage]
        """
        return self._current

    @current.setter
    def current(self, current):
        """Sets the current of this AdditionalInfoResponseInfos.

        This specifies the list of current service alerts based on the specified filters.  # noqa: E501

        :param current: The current of this AdditionalInfoResponseInfos.  # noqa: E501
        :type: list[AdditionalInfoResponseMessage]
        """

        self._current = current

    @property
    def historic(self):
        """Gets the historic of this AdditionalInfoResponseInfos.  # noqa: E501

        This specifies the list of previous service alerts based on the specified filters.  # noqa: E501

        :return: The historic of this AdditionalInfoResponseInfos.  # noqa: E501
        :rtype: list[AdditionalInfoResponseMessage]
        """
        return self._historic

    @historic.setter
    def historic(self, historic):
        """Sets the historic of this AdditionalInfoResponseInfos.

        This specifies the list of previous service alerts based on the specified filters.  # noqa: E501

        :param historic: The historic of this AdditionalInfoResponseInfos.  # noqa: E501
        :type: list[AdditionalInfoResponseMessage]
        """

        self._historic = historic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdditionalInfoResponseInfos, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdditionalInfoResponseInfos):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
