# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.2.1.42
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdditionalInfoResponseMessageAffected(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lines': 'list[AdditionalInfoResponseAffectedLine]',
        'stops': 'list[AdditionalInfoResponseAffectedStop]'
    }

    attribute_map = {
        'lines': 'lines',
        'stops': 'stops'
    }

    def __init__(self, lines=None, stops=None):  # noqa: E501
        """AdditionalInfoResponseMessageAffected - a model defined in Swagger"""  # noqa: E501
        self._lines = None
        self._stops = None
        self.discriminator = None
        if lines is not None:
            self.lines = lines
        if stops is not None:
            self.stops = stops

    @property
    def lines(self):
        """Gets the lines of this AdditionalInfoResponseMessageAffected.  # noqa: E501

        This element contains a list of lines affected by this alert.  # noqa: E501

        :return: The lines of this AdditionalInfoResponseMessageAffected.  # noqa: E501
        :rtype: list[AdditionalInfoResponseAffectedLine]
        """
        return self._lines

    @lines.setter
    def lines(self, lines):
        """Sets the lines of this AdditionalInfoResponseMessageAffected.

        This element contains a list of lines affected by this alert.  # noqa: E501

        :param lines: The lines of this AdditionalInfoResponseMessageAffected.  # noqa: E501
        :type: list[AdditionalInfoResponseAffectedLine]
        """

        self._lines = lines

    @property
    def stops(self):
        """Gets the stops of this AdditionalInfoResponseMessageAffected.  # noqa: E501

        This element contains a list of stops affected by this alert.  # noqa: E501

        :return: The stops of this AdditionalInfoResponseMessageAffected.  # noqa: E501
        :rtype: list[AdditionalInfoResponseAffectedStop]
        """
        return self._stops

    @stops.setter
    def stops(self, stops):
        """Sets the stops of this AdditionalInfoResponseMessageAffected.

        This element contains a list of stops affected by this alert.  # noqa: E501

        :param stops: The stops of this AdditionalInfoResponseMessageAffected.  # noqa: E501
        :type: list[AdditionalInfoResponseAffectedStop]
        """

        self._stops = stops

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdditionalInfoResponseMessageAffected, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdditionalInfoResponseMessageAffected):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
