# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.2.1.42
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TripRequestResponseJourneyLegInterchange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'coords': 'list[list[float]]',
        'desc': 'str',
        'type': 'int'
    }

    attribute_map = {
        'coords': 'coords',
        'desc': 'desc',
        'type': 'type'
    }

    def __init__(self, coords=None, desc=None, type=None):  # noqa: E501
        """TripRequestResponseJourneyLegInterchange - a model defined in Swagger"""  # noqa: E501
        self._coords = None
        self._desc = None
        self._type = None
        self.discriminator = None
        if coords is not None:
            self.coords = coords
        if desc is not None:
            self.desc = desc
        if type is not None:
            self.type = type

    @property
    def coords(self):
        """Gets the coords of this TripRequestResponseJourneyLegInterchange.  # noqa: E501

        This is a list of coordinates that makes up the path of the interchange.   # noqa: E501

        :return: The coords of this TripRequestResponseJourneyLegInterchange.  # noqa: E501
        :rtype: list[list[float]]
        """
        return self._coords

    @coords.setter
    def coords(self, coords):
        """Sets the coords of this TripRequestResponseJourneyLegInterchange.

        This is a list of coordinates that makes up the path of the interchange.   # noqa: E501

        :param coords: The coords of this TripRequestResponseJourneyLegInterchange.  # noqa: E501
        :type: list[list[float]]
        """

        self._coords = coords

    @property
    def desc(self):
        """Gets the desc of this TripRequestResponseJourneyLegInterchange.  # noqa: E501

        This is a description of the interchange.   # noqa: E501

        :return: The desc of this TripRequestResponseJourneyLegInterchange.  # noqa: E501
        :rtype: str
        """
        return self._desc

    @desc.setter
    def desc(self, desc):
        """Sets the desc of this TripRequestResponseJourneyLegInterchange.

        This is a description of the interchange.   # noqa: E501

        :param desc: The desc of this TripRequestResponseJourneyLegInterchange.  # noqa: E501
        :type: str
        """

        self._desc = desc

    @property
    def type(self):
        """Gets the type of this TripRequestResponseJourneyLegInterchange.  # noqa: E501

        This indicates the mode of travel for the interchange. Both `99` and `100` indicate walking.   # noqa: E501

        :return: The type of this TripRequestResponseJourneyLegInterchange.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TripRequestResponseJourneyLegInterchange.

        This indicates the mode of travel for the interchange. Both `99` and `100` indicate walking.   # noqa: E501

        :param type: The type of this TripRequestResponseJourneyLegInterchange.  # noqa: E501
        :type: int
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TripRequestResponseJourneyLegInterchange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TripRequestResponseJourneyLegInterchange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
