# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.2.1.42
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TripTransportationProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_ttb': 'bool',
        'trip_code': 'int'
    }

    attribute_map = {
        'is_ttb': 'isTTB',
        'trip_code': 'tripCode'
    }

    def __init__(self, is_ttb=None, trip_code=None):  # noqa: E501
        """TripTransportationProperties - a model defined in Swagger"""  # noqa: E501
        self._is_ttb = None
        self._trip_code = None
        self.discriminator = None
        if is_ttb is not None:
            self.is_ttb = is_ttb
        if trip_code is not None:
            self.trip_code = trip_code

    @property
    def is_ttb(self):
        """Gets the is_ttb of this TripTransportationProperties.  # noqa: E501

        XXX  # noqa: E501

        :return: The is_ttb of this TripTransportationProperties.  # noqa: E501
        :rtype: bool
        """
        return self._is_ttb

    @is_ttb.setter
    def is_ttb(self, is_ttb):
        """Sets the is_ttb of this TripTransportationProperties.

        XXX  # noqa: E501

        :param is_ttb: The is_ttb of this TripTransportationProperties.  # noqa: E501
        :type: bool
        """

        self._is_ttb = is_ttb

    @property
    def trip_code(self):
        """Gets the trip_code of this TripTransportationProperties.  # noqa: E501

        This is an ID for this journey option.  # noqa: E501

        :return: The trip_code of this TripTransportationProperties.  # noqa: E501
        :rtype: int
        """
        return self._trip_code

    @trip_code.setter
    def trip_code(self, trip_code):
        """Sets the trip_code of this TripTransportationProperties.

        This is an ID for this journey option.  # noqa: E501

        :param trip_code: The trip_code of this TripTransportationProperties.  # noqa: E501
        :type: int
        """

        self._trip_code = trip_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TripTransportationProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TripTransportationProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
