# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.2.1.42
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TripRequestResponseJourneyLegStopProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'wheelchair_access': 'str',
        'downloads': 'list[TripRequestResponseJourneyLegStopDownload]'
    }

    attribute_map = {
        'wheelchair_access': 'WheelchairAccess',
        'downloads': 'downloads'
    }

    def __init__(self, wheelchair_access=None, downloads=None):  # noqa: E501
        """TripRequestResponseJourneyLegStopProperties - a model defined in Swagger"""  # noqa: E501
        self._wheelchair_access = None
        self._downloads = None
        self.discriminator = None
        if wheelchair_access is not None:
            self.wheelchair_access = wheelchair_access
        if downloads is not None:
            self.downloads = downloads

    @property
    def wheelchair_access(self):
        """Gets the wheelchair_access of this TripRequestResponseJourneyLegStopProperties.  # noqa: E501

        Indicates if there is wheelchair access available at this stop.   # noqa: E501

        :return: The wheelchair_access of this TripRequestResponseJourneyLegStopProperties.  # noqa: E501
        :rtype: str
        """
        return self._wheelchair_access

    @wheelchair_access.setter
    def wheelchair_access(self, wheelchair_access):
        """Sets the wheelchair_access of this TripRequestResponseJourneyLegStopProperties.

        Indicates if there is wheelchair access available at this stop.   # noqa: E501

        :param wheelchair_access: The wheelchair_access of this TripRequestResponseJourneyLegStopProperties.  # noqa: E501
        :type: str
        """
        allowed_values = ["true", "false"]  # noqa: E501
        if wheelchair_access not in allowed_values:
            raise ValueError(
                "Invalid value for `wheelchair_access` ({0}), must be one of {1}"  # noqa: E501
                .format(wheelchair_access, allowed_values)
            )

        self._wheelchair_access = wheelchair_access

    @property
    def downloads(self):
        """Gets the downloads of this TripRequestResponseJourneyLegStopProperties.  # noqa: E501

        Describes a list of downloadable files relevant to this location.   # noqa: E501

        :return: The downloads of this TripRequestResponseJourneyLegStopProperties.  # noqa: E501
        :rtype: list[TripRequestResponseJourneyLegStopDownload]
        """
        return self._downloads

    @downloads.setter
    def downloads(self, downloads):
        """Sets the downloads of this TripRequestResponseJourneyLegStopProperties.

        Describes a list of downloadable files relevant to this location.   # noqa: E501

        :param downloads: The downloads of this TripRequestResponseJourneyLegStopProperties.  # noqa: E501
        :type: list[TripRequestResponseJourneyLegStopDownload]
        """

        self._downloads = downloads

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TripRequestResponseJourneyLegStopProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TripRequestResponseJourneyLegStopProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
