# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.2.1.42
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def tfnsw_addinfo_request(self, output_format, **kwargs):  # noqa: E501
        """Provides capability to display all public transport service status and incident information (as published from the Service Alert Messaging System).  # noqa: E501

        This endpoint returns a list of service alerts or additional information about travelling on the public transport network. This list can be filtered by date, route type, route, operator or stop.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_addinfo_request(output_format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str filter_date_valid: This parameter allows you to filter the returned items that are only valid on the specified date. The format of this field is `DD-MM-YYYY`. For example, 12 September 2016 would be represented by `12-09-2016`. 
        :param int filter_mot_type: This parameter allows you to filter the returned items by the modes of transport they affected. Available modes include:  * `1`: Train * `2`: Metro * `4`: Light Rail * `5`: Bus * `7`: Coach * `9`: Ferry * `11`: School Bus  To search for more than one mode, include the parameter multiple times. 
        :param str filter_publication_status: This field can be used so only current alerts are returned, and not historic alerts. 
        :param str itd_l_pxx_sel_stop: This parameter allows you to filter the returned items by its stop ID or global stop ID. For example, to retrieve items that are only relevant to Central Station, you would set this value to `10111010` (stop ID) or `200060` (global stop ID). You can use the `stop_finder` API call to determine the ID for a particular stop. 
        :param str itd_l_pxx_sel_line: This parameter allows you to filter the returned items by line number. For example, `020T1`. You can use this parameter multiple times if you want to search for more than one line number. 
        :param str itd_l_pxx_sel_operator: This parameter allows you to filter the returned items by operator ID. You can use this parameter multiple times if you want to search for more than one line number. 
        :param str filter_pn_line_dir: This parameter allows you to filter the returned items by specific routes. The route is provided in the format `NNN:LLLLL:D`, (NNN: subnet, LLLLL: Route number, D: direction `H`/`R`). You can use this parameter multiple times if you want to search for more than one line number. 
        :param str filter_pn_line_sub: This parameter allows you to filter the returned items by specific routes. The route is provided in the format `NNN:LLLLL:E`, (NNN: subnet, LLLLL: Route number, E: supplement). You can use this parameter multiple times if you want to search for more than one line number. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :return: AdditionalInfoResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.tfnsw_addinfo_request_with_http_info(output_format, **kwargs)  # noqa: E501
        else:
            (data) = self.tfnsw_addinfo_request_with_http_info(output_format, **kwargs)  # noqa: E501
            return data

    def tfnsw_addinfo_request_with_http_info(self, output_format, **kwargs):  # noqa: E501
        """Provides capability to display all public transport service status and incident information (as published from the Service Alert Messaging System).  # noqa: E501

        This endpoint returns a list of service alerts or additional information about travelling on the public transport network. This list can be filtered by date, route type, route, operator or stop.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_addinfo_request_with_http_info(output_format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str filter_date_valid: This parameter allows you to filter the returned items that are only valid on the specified date. The format of this field is `DD-MM-YYYY`. For example, 12 September 2016 would be represented by `12-09-2016`. 
        :param int filter_mot_type: This parameter allows you to filter the returned items by the modes of transport they affected. Available modes include:  * `1`: Train * `2`: Metro * `4`: Light Rail * `5`: Bus * `7`: Coach * `9`: Ferry * `11`: School Bus  To search for more than one mode, include the parameter multiple times. 
        :param str filter_publication_status: This field can be used so only current alerts are returned, and not historic alerts. 
        :param str itd_l_pxx_sel_stop: This parameter allows you to filter the returned items by its stop ID or global stop ID. For example, to retrieve items that are only relevant to Central Station, you would set this value to `10111010` (stop ID) or `200060` (global stop ID). You can use the `stop_finder` API call to determine the ID for a particular stop. 
        :param str itd_l_pxx_sel_line: This parameter allows you to filter the returned items by line number. For example, `020T1`. You can use this parameter multiple times if you want to search for more than one line number. 
        :param str itd_l_pxx_sel_operator: This parameter allows you to filter the returned items by operator ID. You can use this parameter multiple times if you want to search for more than one line number. 
        :param str filter_pn_line_dir: This parameter allows you to filter the returned items by specific routes. The route is provided in the format `NNN:LLLLL:D`, (NNN: subnet, LLLLL: Route number, D: direction `H`/`R`). You can use this parameter multiple times if you want to search for more than one line number. 
        :param str filter_pn_line_sub: This parameter allows you to filter the returned items by specific routes. The route is provided in the format `NNN:LLLLL:E`, (NNN: subnet, LLLLL: Route number, E: supplement). You can use this parameter multiple times if you want to search for more than one line number. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :return: AdditionalInfoResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_format', 'filter_date_valid', 'filter_mot_type', 'filter_publication_status', 'itd_l_pxx_sel_stop', 'itd_l_pxx_sel_line', 'itd_l_pxx_sel_operator', 'filter_pn_line_dir', 'filter_pn_line_sub', 'version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method tfnsw_addinfo_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_format' is set
        if ('output_format' not in params or
                params['output_format'] is None):
            raise ValueError("Missing the required parameter `output_format` when calling `tfnsw_addinfo_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'output_format' in params:
            query_params.append(('outputFormat', params['output_format']))  # noqa: E501
        if 'filter_date_valid' in params:
            query_params.append(('filterDateValid', params['filter_date_valid']))  # noqa: E501
        if 'filter_mot_type' in params:
            query_params.append(('filterMOTType', params['filter_mot_type']))  # noqa: E501
        if 'filter_publication_status' in params:
            query_params.append(('filterPublicationStatus', params['filter_publication_status']))  # noqa: E501
        if 'itd_l_pxx_sel_stop' in params:
            query_params.append(('itdLPxx_selStop', params['itd_l_pxx_sel_stop']))  # noqa: E501
        if 'itd_l_pxx_sel_line' in params:
            query_params.append(('itdLPxx_selLine', params['itd_l_pxx_sel_line']))  # noqa: E501
        if 'itd_l_pxx_sel_operator' in params:
            query_params.append(('itdLPxx_selOperator', params['itd_l_pxx_sel_operator']))  # noqa: E501
        if 'filter_pn_line_dir' in params:
            query_params.append(('filterPNLineDir', params['filter_pn_line_dir']))  # noqa: E501
        if 'filter_pn_line_sub' in params:
            query_params.append(('filterPNLineSub', params['filter_pn_line_sub']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKey']  # noqa: E501

        return self.api_client.call_api(
            '/add_info', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AdditionalInfoResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def tfnsw_coord_request(self, output_format, coord, coord_output_format, incl_filter, type_1, radius_1, **kwargs):  # noqa: E501
        """When given a specific geographical location, this API finds public transport stops, stations, wharfs and points of interest around that location.  # noqa: E501

        This endpoint returns places of interest based on the given coordinate and a radius. The types of POIs can be controlled, so if, for example, you only want Opal resellers returned, you can do so.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_coord_request(output_format, coord, coord_output_format, incl_filter, type_1, radius_1, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str coord: The coordinate is in the format `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first). For example, the following `coord` value can be used to search around Central Station: `151.206290:-33.884080:EPSG:4326`.  (required)
        :param str coord_output_format: This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format.  (required)
        :param int incl_filter: This enables \"advanced filter mode\" on the server, which is required to enable searching using coordinates.  (required)
        :param str type_1: This specifies the type of items to return.  * `GIS_POINT`: GIS points, including Opal resellers (see `inclDrawClasses_1`) * `BUS_POINT`: Stops/stations * `POI_POINT`: Places of interest  The `_1` suffix is an index for this particular filter. You can specify multiple filters by incrementing the suffix for each combination of `type`, `radius` and `inclDrawClasses`. For example, `type_1` means the first filter, `type_2` refers to the second, and so on.  (required)
        :param int radius_1: This indicates the maximum number of metres to search in all directions from the location specified in `coord`. For example, if you use a value of `500`, a `type_1` value of `GIS_POINT` and `inclDrawClasses_1` with a value of `74`, all Opal resellers within 500 metres will be returned. The suffix of `_1` indicates this radius value corresponds to the `type_1` value. If multiple filters are to be included, the appropriate suffix should be updated accordingly.  (required)
        :param int incl_draw_classes_1: This flag changes the list of POIs that are returned. To return Opal resellers, set this value to `74` and `type_1` to `GIS_POINT`.The suffix of `_1` indicates this radius value corresponds to the `type_1` value. If multiple filters are to be included, the appropriate suffix should be updated accordingly. 
        :param str pois_on_map_macro: This field indicates how the returned data is to be used, which in turn impacts whether or not certain locations are returned. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :return: CoordRequestResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.tfnsw_coord_request_with_http_info(output_format, coord, coord_output_format, incl_filter, type_1, radius_1, **kwargs)  # noqa: E501
        else:
            (data) = self.tfnsw_coord_request_with_http_info(output_format, coord, coord_output_format, incl_filter, type_1, radius_1, **kwargs)  # noqa: E501
            return data

    def tfnsw_coord_request_with_http_info(self, output_format, coord, coord_output_format, incl_filter, type_1, radius_1, **kwargs):  # noqa: E501
        """When given a specific geographical location, this API finds public transport stops, stations, wharfs and points of interest around that location.  # noqa: E501

        This endpoint returns places of interest based on the given coordinate and a radius. The types of POIs can be controlled, so if, for example, you only want Opal resellers returned, you can do so.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_coord_request_with_http_info(output_format, coord, coord_output_format, incl_filter, type_1, radius_1, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str coord: The coordinate is in the format `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first). For example, the following `coord` value can be used to search around Central Station: `151.206290:-33.884080:EPSG:4326`.  (required)
        :param str coord_output_format: This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format.  (required)
        :param int incl_filter: This enables \"advanced filter mode\" on the server, which is required to enable searching using coordinates.  (required)
        :param str type_1: This specifies the type of items to return.  * `GIS_POINT`: GIS points, including Opal resellers (see `inclDrawClasses_1`) * `BUS_POINT`: Stops/stations * `POI_POINT`: Places of interest  The `_1` suffix is an index for this particular filter. You can specify multiple filters by incrementing the suffix for each combination of `type`, `radius` and `inclDrawClasses`. For example, `type_1` means the first filter, `type_2` refers to the second, and so on.  (required)
        :param int radius_1: This indicates the maximum number of metres to search in all directions from the location specified in `coord`. For example, if you use a value of `500`, a `type_1` value of `GIS_POINT` and `inclDrawClasses_1` with a value of `74`, all Opal resellers within 500 metres will be returned. The suffix of `_1` indicates this radius value corresponds to the `type_1` value. If multiple filters are to be included, the appropriate suffix should be updated accordingly.  (required)
        :param int incl_draw_classes_1: This flag changes the list of POIs that are returned. To return Opal resellers, set this value to `74` and `type_1` to `GIS_POINT`.The suffix of `_1` indicates this radius value corresponds to the `type_1` value. If multiple filters are to be included, the appropriate suffix should be updated accordingly. 
        :param str pois_on_map_macro: This field indicates how the returned data is to be used, which in turn impacts whether or not certain locations are returned. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :return: CoordRequestResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_format', 'coord', 'coord_output_format', 'incl_filter', 'type_1', 'radius_1', 'incl_draw_classes_1', 'pois_on_map_macro', 'version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method tfnsw_coord_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_format' is set
        if ('output_format' not in params or
                params['output_format'] is None):
            raise ValueError("Missing the required parameter `output_format` when calling `tfnsw_coord_request`")  # noqa: E501
        # verify the required parameter 'coord' is set
        if ('coord' not in params or
                params['coord'] is None):
            raise ValueError("Missing the required parameter `coord` when calling `tfnsw_coord_request`")  # noqa: E501
        # verify the required parameter 'coord_output_format' is set
        if ('coord_output_format' not in params or
                params['coord_output_format'] is None):
            raise ValueError("Missing the required parameter `coord_output_format` when calling `tfnsw_coord_request`")  # noqa: E501
        # verify the required parameter 'incl_filter' is set
        if ('incl_filter' not in params or
                params['incl_filter'] is None):
            raise ValueError("Missing the required parameter `incl_filter` when calling `tfnsw_coord_request`")  # noqa: E501
        # verify the required parameter 'type_1' is set
        if ('type_1' not in params or
                params['type_1'] is None):
            raise ValueError("Missing the required parameter `type_1` when calling `tfnsw_coord_request`")  # noqa: E501
        # verify the required parameter 'radius_1' is set
        if ('radius_1' not in params or
                params['radius_1'] is None):
            raise ValueError("Missing the required parameter `radius_1` when calling `tfnsw_coord_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'output_format' in params:
            query_params.append(('outputFormat', params['output_format']))  # noqa: E501
        if 'coord' in params:
            query_params.append(('coord', params['coord']))  # noqa: E501
        if 'coord_output_format' in params:
            query_params.append(('coordOutputFormat', params['coord_output_format']))  # noqa: E501
        if 'incl_filter' in params:
            query_params.append(('inclFilter', params['incl_filter']))  # noqa: E501
        if 'type_1' in params:
            query_params.append(('type_1', params['type_1']))  # noqa: E501
        if 'radius_1' in params:
            query_params.append(('radius_1', params['radius_1']))  # noqa: E501
        if 'incl_draw_classes_1' in params:
            query_params.append(('inclDrawClasses_1', params['incl_draw_classes_1']))  # noqa: E501
        if 'pois_on_map_macro' in params:
            query_params.append(('PoisOnMapMacro', params['pois_on_map_macro']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKey']  # noqa: E501

        return self.api_client.call_api(
            '/coord', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='CoordRequestResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def tfnsw_dm_request(self, output_format, coord_output_format, type_dm, name_dm, **kwargs):  # noqa: E501
        """Provides capability to provide NSW public transport departure information from a stop, station or wharf including real-time.  # noqa: E501

        This endpoint returns a list of departures for a given location based on the date and time specified. This data can be used to display a \"upcoming departures\" board for a stop.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_dm_request(output_format, coord_output_format, type_dm, name_dm, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str coord_output_format: This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format. (required)
        :param str type_dm: This specifies the type of results expected based on the search input in `name_dm`. By specifying `any`, locations of all types can be returned. Typically, this API call is used for a specific stop, so `stop` should be used along with a stop ID or global stop ID in `name_dm`.  (required)
        :param str name_dm: This is the search term that will be used to find locations. If the combination of this value and `type_dm` results in more than one location found - or `mode` is not set to `direct`, then a list of stops and no departures will be returned. If `type_dm` is set to `stop` then this value can take a stop ID or a global stop ID.  (required)
        :param str mode: This allows the departure board to display directly without going through the stop verification process. Use this when the stop is known. This relies on the given combination of `type_dm` and `name_dm` returning only a single result, otherwise a list of stops and no departures shall be returned. 
        :param str name_key_dm: Setting this parameter to `$USEPOINT$` enables you to request departures for a specific platform within a station. If this isn't used, then departures for all platforms at the stop specified in `name_dm` are returned. 
        :param str itd_date: The reference date used when searching trips, in `YYYYMMDD` format. For instance, 20160901 refers to 1 September 2016. Works in conjunction with the `itdTime` value. If not specified, the current server date is used. 
        :param str itd_time: The reference time used when searching trips, in `HHMM` 24-hour format. For instance, 2215 refers to 10:15 PM. | Works in conjunction with the `itdDate` value. If not specified, the current server time is used. 
        :param str departure_monitor_macro: Including this parameter enables a number of options that result in the departure monitor operating in the same way as the Transport for NSW Trip Planner web site. It is recommended this is enabled, along with the `TfNSWDM` parameter. 
        :param str excluded_means: This parameter which means of transport to exclude from the departure monitor. To exclude one means, select one of the following: `1` = train, `2` = metro, `4` = light rail, `5` = bus, `7` = coach, `9` = ferry, `11` = school bus. `checkbox` allows you to exclude more than one means of transport when used in conjunction with the `exclMOT_<ID>` parameters. 
        :param str excl_mot_1: Excludes train services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_2: Excludes metro services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_4: Excludes light rail services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_5: Excludes bus services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_7: Excludes coach services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_9: Excludes ferry services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_11: Excludes school bus services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str tf_nswdm: Including this parameter enables a number of options that result in the departure monitor operating in the same way as the Transport for NSW Trip Planner web site, including enabling real-time data. It is recommended this is enabled, along with the `departureMonitorMacro` parameter. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :return: DepartureMonitorResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.tfnsw_dm_request_with_http_info(output_format, coord_output_format, type_dm, name_dm, **kwargs)  # noqa: E501
        else:
            (data) = self.tfnsw_dm_request_with_http_info(output_format, coord_output_format, type_dm, name_dm, **kwargs)  # noqa: E501
            return data

    def tfnsw_dm_request_with_http_info(self, output_format, coord_output_format, type_dm, name_dm, **kwargs):  # noqa: E501
        """Provides capability to provide NSW public transport departure information from a stop, station or wharf including real-time.  # noqa: E501

        This endpoint returns a list of departures for a given location based on the date and time specified. This data can be used to display a \"upcoming departures\" board for a stop.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_dm_request_with_http_info(output_format, coord_output_format, type_dm, name_dm, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str coord_output_format: This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format. (required)
        :param str type_dm: This specifies the type of results expected based on the search input in `name_dm`. By specifying `any`, locations of all types can be returned. Typically, this API call is used for a specific stop, so `stop` should be used along with a stop ID or global stop ID in `name_dm`.  (required)
        :param str name_dm: This is the search term that will be used to find locations. If the combination of this value and `type_dm` results in more than one location found - or `mode` is not set to `direct`, then a list of stops and no departures will be returned. If `type_dm` is set to `stop` then this value can take a stop ID or a global stop ID.  (required)
        :param str mode: This allows the departure board to display directly without going through the stop verification process. Use this when the stop is known. This relies on the given combination of `type_dm` and `name_dm` returning only a single result, otherwise a list of stops and no departures shall be returned. 
        :param str name_key_dm: Setting this parameter to `$USEPOINT$` enables you to request departures for a specific platform within a station. If this isn't used, then departures for all platforms at the stop specified in `name_dm` are returned. 
        :param str itd_date: The reference date used when searching trips, in `YYYYMMDD` format. For instance, 20160901 refers to 1 September 2016. Works in conjunction with the `itdTime` value. If not specified, the current server date is used. 
        :param str itd_time: The reference time used when searching trips, in `HHMM` 24-hour format. For instance, 2215 refers to 10:15 PM. | Works in conjunction with the `itdDate` value. If not specified, the current server time is used. 
        :param str departure_monitor_macro: Including this parameter enables a number of options that result in the departure monitor operating in the same way as the Transport for NSW Trip Planner web site. It is recommended this is enabled, along with the `TfNSWDM` parameter. 
        :param str excluded_means: This parameter which means of transport to exclude from the departure monitor. To exclude one means, select one of the following: `1` = train, `2` = metro, `4` = light rail, `5` = bus, `7` = coach, `9` = ferry, `11` = school bus. `checkbox` allows you to exclude more than one means of transport when used in conjunction with the `exclMOT_<ID>` parameters. 
        :param str excl_mot_1: Excludes train services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_2: Excludes metro services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_4: Excludes light rail services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_5: Excludes bus services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_7: Excludes coach services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_9: Excludes ferry services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_11: Excludes school bus services from the departure monitor.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str tf_nswdm: Including this parameter enables a number of options that result in the departure monitor operating in the same way as the Transport for NSW Trip Planner web site, including enabling real-time data. It is recommended this is enabled, along with the `departureMonitorMacro` parameter. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :return: DepartureMonitorResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_format', 'coord_output_format', 'type_dm', 'name_dm', 'mode', 'name_key_dm', 'itd_date', 'itd_time', 'departure_monitor_macro', 'excluded_means', 'excl_mot_1', 'excl_mot_2', 'excl_mot_4', 'excl_mot_5', 'excl_mot_7', 'excl_mot_9', 'excl_mot_11', 'tf_nswdm', 'version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method tfnsw_dm_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_format' is set
        if ('output_format' not in params or
                params['output_format'] is None):
            raise ValueError("Missing the required parameter `output_format` when calling `tfnsw_dm_request`")  # noqa: E501
        # verify the required parameter 'coord_output_format' is set
        if ('coord_output_format' not in params or
                params['coord_output_format'] is None):
            raise ValueError("Missing the required parameter `coord_output_format` when calling `tfnsw_dm_request`")  # noqa: E501
        # verify the required parameter 'type_dm' is set
        if ('type_dm' not in params or
                params['type_dm'] is None):
            raise ValueError("Missing the required parameter `type_dm` when calling `tfnsw_dm_request`")  # noqa: E501
        # verify the required parameter 'name_dm' is set
        if ('name_dm' not in params or
                params['name_dm'] is None):
            raise ValueError("Missing the required parameter `name_dm` when calling `tfnsw_dm_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'output_format' in params:
            query_params.append(('outputFormat', params['output_format']))  # noqa: E501
        if 'coord_output_format' in params:
            query_params.append(('coordOutputFormat', params['coord_output_format']))  # noqa: E501
        if 'mode' in params:
            query_params.append(('mode', params['mode']))  # noqa: E501
        if 'type_dm' in params:
            query_params.append(('type_dm', params['type_dm']))  # noqa: E501
        if 'name_dm' in params:
            query_params.append(('name_dm', params['name_dm']))  # noqa: E501
        if 'name_key_dm' in params:
            query_params.append(('nameKey_dm', params['name_key_dm']))  # noqa: E501
        if 'itd_date' in params:
            query_params.append(('itdDate', params['itd_date']))  # noqa: E501
        if 'itd_time' in params:
            query_params.append(('itdTime', params['itd_time']))  # noqa: E501
        if 'departure_monitor_macro' in params:
            query_params.append(('departureMonitorMacro', params['departure_monitor_macro']))  # noqa: E501
        if 'excluded_means' in params:
            query_params.append(('excludedMeans', params['excluded_means']))  # noqa: E501
        if 'excl_mot_1' in params:
            query_params.append(('exclMOT_1', params['excl_mot_1']))  # noqa: E501
        if 'excl_mot_2' in params:
            query_params.append(('exclMOT_2', params['excl_mot_2']))  # noqa: E501
        if 'excl_mot_4' in params:
            query_params.append(('exclMOT_4', params['excl_mot_4']))  # noqa: E501
        if 'excl_mot_5' in params:
            query_params.append(('exclMOT_5', params['excl_mot_5']))  # noqa: E501
        if 'excl_mot_7' in params:
            query_params.append(('exclMOT_7', params['excl_mot_7']))  # noqa: E501
        if 'excl_mot_9' in params:
            query_params.append(('exclMOT_9', params['excl_mot_9']))  # noqa: E501
        if 'excl_mot_11' in params:
            query_params.append(('exclMOT_11', params['excl_mot_11']))  # noqa: E501
        if 'tf_nswdm' in params:
            query_params.append(('TfNSWDM', params['tf_nswdm']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKey']  # noqa: E501

        return self.api_client.call_api(
            '/departure_mon', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DepartureMonitorResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def tfnsw_stopfinder_request(self, output_format, name_sf, coord_output_format, **kwargs):  # noqa: E501
        """Provides capability to return all NSW public transport stop, station, wharf, points of interest and known addresses to be used for auto-suggest/auto-complete (to be used with the Trip planner and Departure board APIs).  # noqa: E501

        This endpoint returns info about stops that match the search criteria. Matches can be sorted on `matchQuality` to determine the best matches for the given input, while the best match will be indicated by the `isBest` value.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_stopfinder_request(output_format, name_sf, coord_output_format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str name_sf: This is the search term that will be used to find locations. To lookup a coordinate, set `type_sf` to `coord`, and use the following format: `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first). For example, `151.206290:-33.884080:EPSG:4326`. To lookup a stop set `type_sf` to  `stop` and enter the stop id or global stop ID. For example, `10101100`  (required)
        :param str coord_output_format: This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format. (required)
        :param str type_sf: This specifies the type of results expected in the list of returned stops. By specifying `any`, locations of all types can be returned. If you specifically know that you're searching using a coord, specify `coord`. Likewise, if you're using a stop ID or global stop ID as an input, use `stop` for more accurate results. 
        :param str tf_nswsf: Including this parameter enables a number of options that result in the stop finder operating in the same way as the Transport for NSW Trip Planner web site. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :return: StopFinderResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.tfnsw_stopfinder_request_with_http_info(output_format, name_sf, coord_output_format, **kwargs)  # noqa: E501
        else:
            (data) = self.tfnsw_stopfinder_request_with_http_info(output_format, name_sf, coord_output_format, **kwargs)  # noqa: E501
            return data

    def tfnsw_stopfinder_request_with_http_info(self, output_format, name_sf, coord_output_format, **kwargs):  # noqa: E501
        """Provides capability to return all NSW public transport stop, station, wharf, points of interest and known addresses to be used for auto-suggest/auto-complete (to be used with the Trip planner and Departure board APIs).  # noqa: E501

        This endpoint returns info about stops that match the search criteria. Matches can be sorted on `matchQuality` to determine the best matches for the given input, while the best match will be indicated by the `isBest` value.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_stopfinder_request_with_http_info(output_format, name_sf, coord_output_format, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str name_sf: This is the search term that will be used to find locations. To lookup a coordinate, set `type_sf` to `coord`, and use the following format: `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first). For example, `151.206290:-33.884080:EPSG:4326`. To lookup a stop set `type_sf` to  `stop` and enter the stop id or global stop ID. For example, `10101100`  (required)
        :param str coord_output_format: This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format. (required)
        :param str type_sf: This specifies the type of results expected in the list of returned stops. By specifying `any`, locations of all types can be returned. If you specifically know that you're searching using a coord, specify `coord`. Likewise, if you're using a stop ID or global stop ID as an input, use `stop` for more accurate results. 
        :param str tf_nswsf: Including this parameter enables a number of options that result in the stop finder operating in the same way as the Transport for NSW Trip Planner web site. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :return: StopFinderResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_format', 'name_sf', 'coord_output_format', 'type_sf', 'tf_nswsf', 'version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method tfnsw_stopfinder_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_format' is set
        if ('output_format' not in params or
                params['output_format'] is None):
            raise ValueError("Missing the required parameter `output_format` when calling `tfnsw_stopfinder_request`")  # noqa: E501
        # verify the required parameter 'name_sf' is set
        if ('name_sf' not in params or
                params['name_sf'] is None):
            raise ValueError("Missing the required parameter `name_sf` when calling `tfnsw_stopfinder_request`")  # noqa: E501
        # verify the required parameter 'coord_output_format' is set
        if ('coord_output_format' not in params or
                params['coord_output_format'] is None):
            raise ValueError("Missing the required parameter `coord_output_format` when calling `tfnsw_stopfinder_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'output_format' in params:
            query_params.append(('outputFormat', params['output_format']))  # noqa: E501
        if 'type_sf' in params:
            query_params.append(('type_sf', params['type_sf']))  # noqa: E501
        if 'name_sf' in params:
            query_params.append(('name_sf', params['name_sf']))  # noqa: E501
        if 'coord_output_format' in params:
            query_params.append(('coordOutputFormat', params['coord_output_format']))  # noqa: E501
        if 'tf_nswsf' in params:
            query_params.append(('TfNSWSF', params['tf_nswsf']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKey']  # noqa: E501

        return self.api_client.call_api(
            '/stop_finder', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StopFinderResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def tfnsw_trip_request2(self, output_format, coord_output_format, dep_arr_macro, type_origin, name_origin, type_destination, name_destination, **kwargs):  # noqa: E501
        """Provides capability to provide NSW public transport trip plan options, including walking and driving legs and real-time information.  # noqa: E501

        This endpoint is used to find a list of journeys between two locations at the specified date and time. For example, if the user is at the Airport and wants to get to Manly using public transport but isn't sure how exactly, this call will tell them exactly which train, bus, ferry or light rail to catch, and between which stops. It is extremely detailed, and includes the the specific path the vehicle(s) will take.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_trip_request2(output_format, coord_output_format, dep_arr_macro, type_origin, name_origin, type_destination, name_destination, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str coord_output_format: This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format. (required)
        :param str dep_arr_macro: This value anchors the requested date time. If set to `dep`, then trips *departing after* the specified date/time *at the specified location* are included. If set to `arr`, then trips *arriving before* the specified time *at its destination stop* are included. Works in conjunctions with the `itdDate` and `itdTime` values.  (required)
        :param str type_origin: This is the type of data specified in the `name_origin` field. The origin indicates the starting point when searching for journeys. The best way to use the trip planner is to use use `any` for this field then specify a valid location ID in `type_origin`, or to use `coord` in this field and a correctly formatted coordinate in `type_origin`.  (required)
        :param str name_origin: This value is used to indicate the starting point when searching for journeys. This value can be one of three things: A valid location/stop ID (for example, `10101100` indicates Central Station - this can be determined using `stop_finder`). A valid global stop ID (for example, `200060` indicates Central Station - this can be determined using `stop_finder`) Coordinates in the format `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first).  (required)
        :param str type_destination: This is the type of data specified in the `name_destination` field. The origin indicates the finishing point when searching for journeys. The best way to use the trip planner is to use use `any` for this field then specify a valid location ID in `type_destination`, or to use `coord` in this field and a correctly formatted coordinate in `type_destination`.  (required)
        :param str name_destination: This value is used to indicate the finishing point when searching for journeys. This value can be one of three things: A valid location/stop ID (for example, `10101100` indicates Central Station - this can be determined using `stop_finder`). A valid global stop ID (for example, `200060` indicates Central Station - this can be determined using `stop_finder`) Coordinates in the format `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first).  (required)
        :param str itd_date: The reference date used when searching trips, in `YYYYMMDD` format. For instance, `20160901` refers to 1 September 2016. Works in conjunction with the `itdTime` and `depArrMacro` values. If not specified, the current server date is used. 
        :param str itd_time: The reference time used when searching trips, in `HHMM` 24-hour format. For instance, `2215` refers to 10:15 PM. | Works in conjunction with the `itdDate` and `depArrMacro` values. If not specified, the current server time is used. 
        :param int calc_number_of_trips: This parameter indicates the maximum number of trips to returned. Fewer trips may be returned anyway, depending on the available public transport services. 
        :param str wheelchair: Including this parameter (regardless of its value) ensures that only wheelchair-accessible options are returned. 
        :param str excluded_means: This parameter which means of transport to exclude from the trip plan. To exclude one means, select one of the following: `1` = train, `2` = metro, `4` = light rail, `5` = bus, `7` = coach, `9` = ferry, `11` = school bus. `checkbox` allows you to exclude more than one means of transport when used in conjunction with the `exclMOT_<ID>` parameters. 
        :param str excl_mot_1: Excludes train services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_2: Excludes metro services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_4: Excludes light rail services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_5: Excludes bus services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_7: Excludes coach services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_9: Excludes ferry services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_11: Excludes school bus services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str tf_nswtr: Including this parameter enables a number of options that result in this API call operating in the same way as the Transport for NSW Trip Planner web site, including enabling real-time data. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :param int it_options_active: This parameter activates the options for individual transport. If the parameter is disabled, the parameters concerning individual transport will not be taken into account. possible values are 0 and 1 
        :param bool compute_monomodal_trip_bicycle: Activates the calculation of a monomodal trip, i.e., a trip that takes place exclusively with the means of transport <means of transport>, e.g., with bicycle. Note 1: In order to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Note 2: If no monomodal trip with the means of transport <means of transport> is calculated despite the parameter, the maximum time is often set too low. The parameter MaxITTime applies to all means of transport, the parameter MaxITTime<means of transport>to the means of transport <means of transport> (e.g., MaxITTime107). These parameters are located in the [Parameters] section or are added to it. The configuration can be alternatively overridden bythe maxTime<Transport means> parameter. 
        :param int cycle_speed: The value of the <speed> parameter is used to specify the speed of cycle travel in kilometers per hour.Note: In order to use this parameter, the options for individual transport must be activated with itOptionsActive=1. If the parameter is to be specified together with a profile, the bikeProfSpeed parameter can be used.The parameter “'cycleSpeed” specifies the desired real speed of the user for the bike route, which overwrites the speed in the SpeedSettings of the corresponding “bikeProfSpeed”. 
        :param str bike_prof_speed: With the parameter 'bikeProfSpeed' a bike profile name is passed 
        :param int max_time_bicycle: The value of the this parameter sets the maximum time to be covered by the means of cycling. The time is specified in minutes. Note: To use this parameter, the options for individual transport must be enabled with itOptionsActive=1 
        :param int only_it_bicycle: Restricts the calculation to trips with the bikes only. Note: To be able to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Possible values are 1, true, on 
        :param int use_elevation_data: If this parameter is active, the elevation data is taken into account in the trip calculation for all means of transport and output in a route description for each individual transport section. Note: To be able to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Possible values are 1, true, on 
        :param int elev_fac: This parameter specifies the maximum slope for bike routes. Roads with a slope greater than the specified?? one are avoided. The slope is specified by a factor <factor> whose value range is [0..100]. By default, the value of the parameter is 50 
        :return: TripRequestResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.tfnsw_trip_request2_with_http_info(output_format, coord_output_format, dep_arr_macro, type_origin, name_origin, type_destination, name_destination, **kwargs)  # noqa: E501
        else:
            (data) = self.tfnsw_trip_request2_with_http_info(output_format, coord_output_format, dep_arr_macro, type_origin, name_origin, type_destination, name_destination, **kwargs)  # noqa: E501
            return data

    def tfnsw_trip_request2_with_http_info(self, output_format, coord_output_format, dep_arr_macro, type_origin, name_origin, type_destination, name_destination, **kwargs):  # noqa: E501
        """Provides capability to provide NSW public transport trip plan options, including walking and driving legs and real-time information.  # noqa: E501

        This endpoint is used to find a list of journeys between two locations at the specified date and time. For example, if the user is at the Airport and wants to get to Manly using public transport but isn't sure how exactly, this call will tell them exactly which train, bus, ferry or light rail to catch, and between which stops. It is extremely detailed, and includes the the specific path the vehicle(s) will take.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tfnsw_trip_request2_with_http_info(output_format, coord_output_format, dep_arr_macro, type_origin, name_origin, type_destination, name_destination, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str output_format: Used to set the response data type. This documentation only covers responses that use the JSON format. Setting the `outputFormat` value to `rapidJSON` is required to enable JSON output.  (required)
        :param str coord_output_format: This specifies the format the coordinates are returned in. While other variations are available, the `EPSG:4326` format will return the widely-used format. (required)
        :param str dep_arr_macro: This value anchors the requested date time. If set to `dep`, then trips *departing after* the specified date/time *at the specified location* are included. If set to `arr`, then trips *arriving before* the specified time *at its destination stop* are included. Works in conjunctions with the `itdDate` and `itdTime` values.  (required)
        :param str type_origin: This is the type of data specified in the `name_origin` field. The origin indicates the starting point when searching for journeys. The best way to use the trip planner is to use use `any` for this field then specify a valid location ID in `type_origin`, or to use `coord` in this field and a correctly formatted coordinate in `type_origin`.  (required)
        :param str name_origin: This value is used to indicate the starting point when searching for journeys. This value can be one of three things: A valid location/stop ID (for example, `10101100` indicates Central Station - this can be determined using `stop_finder`). A valid global stop ID (for example, `200060` indicates Central Station - this can be determined using `stop_finder`) Coordinates in the format `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first).  (required)
        :param str type_destination: This is the type of data specified in the `name_destination` field. The origin indicates the finishing point when searching for journeys. The best way to use the trip planner is to use use `any` for this field then specify a valid location ID in `type_destination`, or to use `coord` in this field and a correctly formatted coordinate in `type_destination`.  (required)
        :param str name_destination: This value is used to indicate the finishing point when searching for journeys. This value can be one of three things: A valid location/stop ID (for example, `10101100` indicates Central Station - this can be determined using `stop_finder`). A valid global stop ID (for example, `200060` indicates Central Station - this can be determined using `stop_finder`) Coordinates in the format `LONGITUDE:LATITUDE:EPSG:4326` (Note that longitude is first).  (required)
        :param str itd_date: The reference date used when searching trips, in `YYYYMMDD` format. For instance, `20160901` refers to 1 September 2016. Works in conjunction with the `itdTime` and `depArrMacro` values. If not specified, the current server date is used. 
        :param str itd_time: The reference time used when searching trips, in `HHMM` 24-hour format. For instance, `2215` refers to 10:15 PM. | Works in conjunction with the `itdDate` and `depArrMacro` values. If not specified, the current server time is used. 
        :param int calc_number_of_trips: This parameter indicates the maximum number of trips to returned. Fewer trips may be returned anyway, depending on the available public transport services. 
        :param str wheelchair: Including this parameter (regardless of its value) ensures that only wheelchair-accessible options are returned. 
        :param str excluded_means: This parameter which means of transport to exclude from the trip plan. To exclude one means, select one of the following: `1` = train, `2` = metro, `4` = light rail, `5` = bus, `7` = coach, `9` = ferry, `11` = school bus. `checkbox` allows you to exclude more than one means of transport when used in conjunction with the `exclMOT_<ID>` parameters. 
        :param str excl_mot_1: Excludes train services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_2: Excludes metro services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_4: Excludes light rail services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_5: Excludes bus services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_7: Excludes coach services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_9: Excludes ferry services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str excl_mot_11: Excludes school bus services from the trip plan.  Must be used in conjunction with `excludedMeans=checkbox` 
        :param str tf_nswtr: Including this parameter enables a number of options that result in this API call operating in the same way as the Transport for NSW Trip Planner web site, including enabling real-time data. 
        :param str version: Indicates which version of the API the caller is expecting for both request and response data. Note that if this version differs from the version listed above then the returned data may not be as expected. 
        :param int it_options_active: This parameter activates the options for individual transport. If the parameter is disabled, the parameters concerning individual transport will not be taken into account. possible values are 0 and 1 
        :param bool compute_monomodal_trip_bicycle: Activates the calculation of a monomodal trip, i.e., a trip that takes place exclusively with the means of transport <means of transport>, e.g., with bicycle. Note 1: In order to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Note 2: If no monomodal trip with the means of transport <means of transport> is calculated despite the parameter, the maximum time is often set too low. The parameter MaxITTime applies to all means of transport, the parameter MaxITTime<means of transport>to the means of transport <means of transport> (e.g., MaxITTime107). These parameters are located in the [Parameters] section or are added to it. The configuration can be alternatively overridden bythe maxTime<Transport means> parameter. 
        :param int cycle_speed: The value of the <speed> parameter is used to specify the speed of cycle travel in kilometers per hour.Note: In order to use this parameter, the options for individual transport must be activated with itOptionsActive=1. If the parameter is to be specified together with a profile, the bikeProfSpeed parameter can be used.The parameter “'cycleSpeed” specifies the desired real speed of the user for the bike route, which overwrites the speed in the SpeedSettings of the corresponding “bikeProfSpeed”. 
        :param str bike_prof_speed: With the parameter 'bikeProfSpeed' a bike profile name is passed 
        :param int max_time_bicycle: The value of the this parameter sets the maximum time to be covered by the means of cycling. The time is specified in minutes. Note: To use this parameter, the options for individual transport must be enabled with itOptionsActive=1 
        :param int only_it_bicycle: Restricts the calculation to trips with the bikes only. Note: To be able to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Possible values are 1, true, on 
        :param int use_elevation_data: If this parameter is active, the elevation data is taken into account in the trip calculation for all means of transport and output in a route description for each individual transport section. Note: To be able to use this parameter, the options for individual transport must be activated with itOptionsActive=1. Possible values are 1, true, on 
        :param int elev_fac: This parameter specifies the maximum slope for bike routes. Roads with a slope greater than the specified?? one are avoided. The slope is specified by a factor <factor> whose value range is [0..100]. By default, the value of the parameter is 50 
        :return: TripRequestResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['output_format', 'coord_output_format', 'dep_arr_macro', 'type_origin', 'name_origin', 'type_destination', 'name_destination', 'itd_date', 'itd_time', 'calc_number_of_trips', 'wheelchair', 'excluded_means', 'excl_mot_1', 'excl_mot_2', 'excl_mot_4', 'excl_mot_5', 'excl_mot_7', 'excl_mot_9', 'excl_mot_11', 'tf_nswtr', 'version', 'it_options_active', 'compute_monomodal_trip_bicycle', 'cycle_speed', 'bike_prof_speed', 'max_time_bicycle', 'only_it_bicycle', 'use_elevation_data', 'elev_fac']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method tfnsw_trip_request2" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'output_format' is set
        if ('output_format' not in params or
                params['output_format'] is None):
            raise ValueError("Missing the required parameter `output_format` when calling `tfnsw_trip_request2`")  # noqa: E501
        # verify the required parameter 'coord_output_format' is set
        if ('coord_output_format' not in params or
                params['coord_output_format'] is None):
            raise ValueError("Missing the required parameter `coord_output_format` when calling `tfnsw_trip_request2`")  # noqa: E501
        # verify the required parameter 'dep_arr_macro' is set
        if ('dep_arr_macro' not in params or
                params['dep_arr_macro'] is None):
            raise ValueError("Missing the required parameter `dep_arr_macro` when calling `tfnsw_trip_request2`")  # noqa: E501
        # verify the required parameter 'type_origin' is set
        if ('type_origin' not in params or
                params['type_origin'] is None):
            raise ValueError("Missing the required parameter `type_origin` when calling `tfnsw_trip_request2`")  # noqa: E501
        # verify the required parameter 'name_origin' is set
        if ('name_origin' not in params or
                params['name_origin'] is None):
            raise ValueError("Missing the required parameter `name_origin` when calling `tfnsw_trip_request2`")  # noqa: E501
        # verify the required parameter 'type_destination' is set
        if ('type_destination' not in params or
                params['type_destination'] is None):
            raise ValueError("Missing the required parameter `type_destination` when calling `tfnsw_trip_request2`")  # noqa: E501
        # verify the required parameter 'name_destination' is set
        if ('name_destination' not in params or
                params['name_destination'] is None):
            raise ValueError("Missing the required parameter `name_destination` when calling `tfnsw_trip_request2`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'output_format' in params:
            query_params.append(('outputFormat', params['output_format']))  # noqa: E501
        if 'coord_output_format' in params:
            query_params.append(('coordOutputFormat', params['coord_output_format']))  # noqa: E501
        if 'dep_arr_macro' in params:
            query_params.append(('depArrMacro', params['dep_arr_macro']))  # noqa: E501
        if 'itd_date' in params:
            query_params.append(('itdDate', params['itd_date']))  # noqa: E501
        if 'itd_time' in params:
            query_params.append(('itdTime', params['itd_time']))  # noqa: E501
        if 'type_origin' in params:
            query_params.append(('type_origin', params['type_origin']))  # noqa: E501
        if 'name_origin' in params:
            query_params.append(('name_origin', params['name_origin']))  # noqa: E501
        if 'type_destination' in params:
            query_params.append(('type_destination', params['type_destination']))  # noqa: E501
        if 'name_destination' in params:
            query_params.append(('name_destination', params['name_destination']))  # noqa: E501
        if 'calc_number_of_trips' in params:
            query_params.append(('calcNumberOfTrips', params['calc_number_of_trips']))  # noqa: E501
        if 'wheelchair' in params:
            query_params.append(('wheelchair', params['wheelchair']))  # noqa: E501
        if 'excluded_means' in params:
            query_params.append(('excludedMeans', params['excluded_means']))  # noqa: E501
        if 'excl_mot_1' in params:
            query_params.append(('exclMOT_1', params['excl_mot_1']))  # noqa: E501
        if 'excl_mot_2' in params:
            query_params.append(('exclMOT_2', params['excl_mot_2']))  # noqa: E501
        if 'excl_mot_4' in params:
            query_params.append(('exclMOT_4', params['excl_mot_4']))  # noqa: E501
        if 'excl_mot_5' in params:
            query_params.append(('exclMOT_5', params['excl_mot_5']))  # noqa: E501
        if 'excl_mot_7' in params:
            query_params.append(('exclMOT_7', params['excl_mot_7']))  # noqa: E501
        if 'excl_mot_9' in params:
            query_params.append(('exclMOT_9', params['excl_mot_9']))  # noqa: E501
        if 'excl_mot_11' in params:
            query_params.append(('exclMOT_11', params['excl_mot_11']))  # noqa: E501
        if 'tf_nswtr' in params:
            query_params.append(('TfNSWTR', params['tf_nswtr']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501
        if 'it_options_active' in params:
            query_params.append(('itOptionsActive', params['it_options_active']))  # noqa: E501
        if 'compute_monomodal_trip_bicycle' in params:
            query_params.append(('computeMonomodalTripBicycle', params['compute_monomodal_trip_bicycle']))  # noqa: E501
        if 'cycle_speed' in params:
            query_params.append(('cycleSpeed', params['cycle_speed']))  # noqa: E501
        if 'bike_prof_speed' in params:
            query_params.append(('bikeProfSpeed', params['bike_prof_speed']))  # noqa: E501
        if 'max_time_bicycle' in params:
            query_params.append(('maxTimeBicycle', params['max_time_bicycle']))  # noqa: E501
        if 'only_it_bicycle' in params:
            query_params.append(('onlyITBicycle', params['only_it_bicycle']))  # noqa: E501
        if 'use_elevation_data' in params:
            query_params.append(('useElevationData', params['use_elevation_data']))  # noqa: E501
        if 'elev_fac' in params:
            query_params.append(('elevFac', params['elev_fac']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKey']  # noqa: E501

        return self.api_client.call_api(
            '/trip', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='TripRequestResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
